name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build using docker
      uses: docker/build-push-action@v2
      with:
        target: app
        push: true
        tags: |
          smoretto/alps:latest
          smoretto/alps:1.0.0
          ghcr.io/smoretto/alps:latest
          ghcr.io/smoretto/alps:1.0.0
